version: '2'
services:
  nginx:
    image: nginx:alpine
    ports:
        - "3000:80"
    volumes:
        - ./nginx-conf.d:/etc/nginx/conf.d:ro
        - react-app:/react-app
    depends_on:
        - frontend
        - backend
  frontend:
    build: frontend
    volumes:
        - ../../frontend:/app
        - react-app:/app/build
    expose:
        - "3000"
    environment:
        - BUNDLE
  backend:
    build: backend
    volumes:
        - ../../backend:/app
    expose:
        - "5000"
    ports:
        - "5000:5000"
    environment:
        - INDI_SERVER_HOST
        - INDI_SERVER_PORT
        - WEB_THREADS
        - DEV_BACKEND_SERVER
        - GUNICORN_WORKER_CLASS
  
volumes:
  react-app:
